services:
  postgres:
    image: postgres:15-alpine
    container_name: sales-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pass
      POSTGRES_DB: sales_db
    ports:
      - "5433:5432"  # Port différent pour éviter les conflits
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sales_user -d sales_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  sales-service:
    build: .
    container_name: sales-service
    restart: unless-stopped
    ports:
      - "3034:3034"
    environment:
      DATABASE_URL: "postgresql://sales_user:sales_pass@postgres:5432/sales_db"
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
