version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db-data:
