module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    testMatch: ["**/tests/**/*.test.ts"],
    collectCoverageFrom: [
        "src/backend/**/*.ts",
        "!src/backend/**/*.d.ts",
        "!src/backend/server.ts",
        "!src/backend/generate-swagger.ts",
        "!src/backend/swagger.ts",
        "!src/backend/interfaces/routes/**",
        "!src/backend/utils/logger.ts",
        "!src/backend/metrics.ts",
        "!src/tests/scripts/**",
        "!src/backend/infrastructure/prisma/PrismaClient.ts",
        "!src/backend/application/services/DatabaseMetricsService.ts",
        "!src/backend/application/services/RedisCacheService.ts",
        "!src/backend/interfaces/middlewares/cacheMiddleware.ts",
    ],
    coverageDirectory: "coverage",
    coverageReporters: ["text", "lcov", "html"],
    setupFilesAfterEnv: ["<rootDir>/tests/mocks/setup/testSetup.ts"],
    modulePathIgnorePatterns: ["<rootDir>/dist/"],
    clearMocks: true,
    resetMocks: true,
    restoreMocks: true,
};
