global:
  scrape_interval: 15s

scrape_configs:
  # Backend instances
  - job_name: 'backend-cluster'
    static_configs:
      - targets: 
          - 'backend-1:3030'
          - 'backend-2:3030'
          # - 'backend-3:3030'
          # - 'backend-4:3030'
          # - 'backend-5:3030'
    metrics_path: /metrics
    scrape_interval: 10s