name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pylint black pytest
      
      - name: Run linters
        run: |
          pylint *.py
          black --check *.py

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/log430-lab0:latest .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/log430-lab0:latest
